### ISSUE TITLE
error reading from stdin

### ISSUE THREAD

**Issue by renanqts** [lloydroc/ebyte-sx1276#21]
suddenly I faced with 

```
e32_poll_gpio_aux: received 1 bytes for a total of 28 bytes from uart
�>>���>>�>>>���p�o�����e32_poll_input_enable
e32_poll_gpio_aux: transition from IDLE to RX state
e32_poll_input_disable
ERROR [EBADF Bad file descriptor] error reading from stdin
```
after using version 1.10.0.

I'm running it in a PI 4 this time.
Any clue on this issue?

**Comment by lloydroc** [comment]
Was this running in a container?

**Comment by renanqts** [comment]
in both case, it is failing like that

**Comment by lloydroc** [comment]
Firstly, I'm really curious how you're seeing this. I run this regularly on a Pi4, PiB+ and Pi Zero and have never seen this. What command are you using to run it? Is it simply `e32`?

How I'm reading the output you have is:
- I assume stdin is enabled, which then you must be in a tty (terminal). Do you ever see `waiting for input from the terminal` in the log output?
- I presume it was previously in the RX state to print the output of 28 bytes then it went to IDLE
- It prints the 28 total bytes to stdout. Now this output is some non-ascii values which I suppose I was not expecting to go out stdout. When I run it as a daemon it will close stdin, stdout and this wouldn't happen. I might need to test this causing some issue with stdin.
- We're now in the RX state and we disable inputs but here is what is strange as perhaps we never disable them because `opts->input_standard = 0`? Not sure how that could be.
- We then get `EBADF` the only way this can happen is `opts->input_standard = 1` else we couldn't have polled std and read from it.

So 🤷‍♂️ when I look through the code I don't see how it could be possible. Would you mind me sending the command you ran to get here and the full log output where it prints out the options?

Also, for your use case do you care to have `stdin` and `stdout` even open? Do you care about typing input and seeing in the terminal output? I assume it's better if `stdin` is disabled completely and for the container we need `stdout` for the logs.

**Comment by lloydroc** [comment]
I ran a test sending non-ascii text.

Sent this from a raspberry pi B+:
```
$  e32
waiting for input from the terminal
i�y��}ל
```

Received this on a Pi Zero:
```
 e32 -v
option reset is 0
option help is 0
option verbose is 1
option status is 0
option mode is -1
option GPIO M0 Pin is 23
option GPIO M1 Pin is 24
option GPIO AUX Pin is 18
option daemon 0
option TTY Name is /dev/serial0
option socket unix data file desciptor -1
option socket unix control file desciptor -1
opened /dev/serial0
read mode 0
mode 0 unchanged
waiting for input from the terminal
e32_poll_input_enable
e32_poll_gpio_aux: transition from IDLE to RX state
e32_poll_input_disable
e32_poll_uart: received 1 bytes for a total of 1 bytes from uart
e32_poll_uart: received 1 bytes for a total of 2 bytes from uart
e32_poll_uart: received 1 bytes for a total of 3 bytes from uart
e32_poll_uart: received 1 bytes for a total of 4 bytes from uart
e32_poll_uart: received 1 bytes for a total of 5 bytes from uart
e32_poll_uart: received 1 bytes for a total of 6 bytes from uart
e32_poll_uart: received 1 bytes for a total of 7 bytes from uart
e32_poll_uart: received 1 bytes for a total of 8 bytes from uart
e32_poll_uart: received 1 bytes for a total of 9 bytes from uart
e32_poll_uart: received 1 bytes for a total of 10 bytes from uart
e32_poll_uart: received 1 bytes for a total of 11 bytes from uart
e32_poll_uart: received 1 bytes for a total of 12 bytes from uart
e32_poll_uart: received 1 bytes for a total of 13 bytes from uart
e32_poll_uart: received 2 bytes for a total of 15 bytes from uart
e32_poll_gpio_aux: transition from RX to IDLE state
e32_poll_gpio_aux: additional sleep for uart buffered data
e32_poll_gpio_aux: received 0 bytes for a total of 15 bytes from uart
69efbfbd79efbfbdefbfbd7dd79c0a
i�y��}ל
e32_poll_input_enable

```

Received this on a Raspberry Pi 4:
```
$  e32 -v
option reset is 0
option help is 0
option verbose is 1
option status is 0
option mode is -1
option GPIO M0 Pin is 23
option GPIO M1 Pin is 24
option GPIO AUX Pin is 18
option daemon 0
option TTY Name is /dev/serial0
option socket unix data file desciptor -1
option socket unix control file desciptor -1
opened /dev/serial0
read mode 0
mode 0 unchanged
waiting for input from the terminal
e32_poll_input_enable
e32_poll_gpio_aux: transition from IDLE to RX state
e32_poll_input_disable
e32_poll_uart: received 1 bytes for a total of 1 bytes from uart
e32_poll_uart: received 1 bytes for a total of 2 bytes from uart
e32_poll_uart: received 1 bytes for a total of 3 bytes from uart
e32_poll_uart: received 1 bytes for a total of 4 bytes from uart
e32_poll_uart: received 1 bytes for a total of 5 bytes from uart
e32_poll_uart: received 1 bytes for a total of 6 bytes from uart
e32_poll_uart: received 1 bytes for a total of 7 bytes from uart
e32_poll_uart: received 1 bytes for a total of 8 bytes from uart
e32_poll_uart: received 1 bytes for a total of 9 bytes from uart
e32_poll_uart: received 1 bytes for a total of 10 bytes from uart
e32_poll_uart: received 1 bytes for a total of 11 bytes from uart
e32_poll_uart: received 1 bytes for a total of 12 bytes from uart
e32_poll_uart: received 1 bytes for a total of 13 bytes from uart
e32_poll_uart: received 1 bytes for a total of 14 bytes from uart
e32_poll_uart: received 1 bytes for a total of 15 bytes from uart
e32_poll_gpio_aux: transition from RX to IDLE state
e32_poll_gpio_aux: received 0 bytes for a total of 15 bytes from uart
69efbfbd79efbfbdefbfbd7dd79c0a
i�y��}ל
e32_poll_input_enable

```

**Comment by renanqts** [comment]
@lloydroc just to let you know. I'm "refactoring" my cluster, I guess this issue will go away after. Give me some time, I will leté you know after

**Comment by renanqts** [comment]
@lloydroc thanks for helping. I'm going to close it. I change my topology here and now I had a rpi zero only for this.

**Comment by lloydroc** [comment]
Thanks. Any idea how these problems could have happened and on what
Raspberry Pi? Would like to try to fix them if possible.

You're not seeing any problems on your end and everything is working fine?

Lloyd

**Comment by renanqts** [comment]
I had this issue in rpi 4 running ubuntu 20.04. I guess it was some miss configuration there, but I don't have any idea which one.
