### ISSUE TITLE
Command e32 --status dosn`t give feedback (stuck)

### ISSUE THREAD

**Issue by Yassineelkasmy** [lloydroc/ebyte-sx1276#23]
## Problem: 
The command e32 --status hangs forever without output or feedback.

# Raspberry Pi Command Terminal (e32 --status command):
![WhatsApp Image 2022-01-14 at 11 18 46](https://user-images.githubusercontent.com/18315060/149499515-b2f7d418-a6e9-4e2e-b932-9c2f82c9dc64.jpeg)

# Lora E32 Wiring :

![WhatsApp Image 2022-01-14 at 11 14 49](https://user-images.githubusercontent.com/18315060/149499302-e36330a3-9447-447b-9733-34f2d2d30b6b.jpeg)

# Raspberry Pi 4 Wiring:
![WhatsApp Image 2022-01-14 at 11 15 04](https://user-images.githubusercontent.com/18315060/149499327-5e24c9e7-5439-478c-a2a8-549df846f01a.jpeg)

# TTy port verification (ls -l /dev/ttyAMA0):
![WhatsApp Image 2022-01-14 at 11 21 34](https://user-images.githubusercontent.com/18315060/149499978-b54668a2-cdf6-40d3-ba8a-d439b5355337.jpeg)

# Any help will be appreciated !

**Comment by lloydroc** [comment]
Thanks for all the information. I'll be happy to help! I'm also surprised
to here that it never times out and "hangs forever".

Can you get me this (assuming wiring is correct):
What Raspberry Pi Version are you using?
What is the version when you run a e32 -h
Can you get me the output of e32 -v --status
Is there perhaps another e32 process running in the background if you do a ps
aux | grep e32

Lloyd

**Comment by Yassineelkasmy** [comment]
Thanks for the reply i realy appreciate it. Right now i can't give u more information until monday 😅.
I believe that we r using the latest e32 cuz i just installed it today directly from your repository , and we r using Raspberry Pi 4 2018. 
I will provide you with all other details in monday.

**Comment by lloydroc** [comment]
Hello, just checking in. Did you get it working?

**Comment by Yassineelkasmy** [comment]
Unfortunately our class on Monday has been delayed , I can touch the hardware only in class ...

**Comment by Yassineelkasmy** [comment]
## e32 version 
Version 1.10.0

## ps aux | grep e32
pi        5018  0.0  0.0   7452   548 pts/0    S+   09:19   0:00 grep --color=auto e32

## e32 -v --status
option reset is 0
option help is 0
option verbose is 1
option status is 1
option mode is -1
option GPIO M0 Pin is 23
option GPIO M1 Pin is 24
option GPIO AUX Pin is 18
option daemon 0
option TTY Name is /dev/serial0
option socket unix data file desciptor -1
option socket unix control file desciptor -1
opened /dev/serial0
read mode 3
mode 3 unchanged
writing version command
reading version
ERROR [?UNKNOWN? Success] timed out

unable to read version

**Comment by lloydroc** [comment]
Ok thanks,

What is the output of this:

***@***.***:~ $ ls -l /dev/serial0
lrwxrwxrwx 1 root root 10 Dec  1 13:49 /dev/serial0 -> /dev/ttyS0
***@***.***:~ $ ls -l /dev/ttyS0
crw-rw---- 1 root dialout 4, 64 Feb 11 19:02 /dev/ttyS0
***@***.***:~# groups pi
pi : pi adm dialout cdrom sudo audio video plugdev games users input netdev
spi i2c gpio docker
***@***.***:~# stty -F /dev/serial0 -a
speed 9600 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2
= <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 0; time = 5;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon
-ixoff -iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0
vt0 ff0
-isig -icanon -iexten -echo echoe echok -echonl -noflsh -xcase -tostop
-echoprt echoctl echoke -flusho -extproc
***@***.***:~#

You also have this?
[image: image.png]
Lloyd

**Comment by Yassineelkasmy** [comment]
## This is the output of the commands you put

root@raspberrypi:/home/pi# ls -l /dev/serial0
lrwxrwxrwx 1 root root 5 Feb 11 13:17 /dev/serial0 -> ttyS0
root@raspberrypi:/home/pi# groups pi
pi : pi adm dialout cdrom sudo audio video plugdev games users input netdev spi i2c gpio lpadmin
root@raspberrypi:/home/pi# stty -F /dev/serial0 -a
speed 57600 baud; rows 24; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff
-iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon -iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt
-echoctl -echoke -flusho -extproc

## By the way the command e32 -s still hanging

root@raspberrypi:/home/pi# e32 -s -v
option reset is 0
option help is 0
option verbose is 1
option status is 1
option mode is -1
option GPIO M0 Pin is 23
option GPIO M1 Pin is 24
option GPIO AUX Pin is 18
option daemon 0
option TTY Name is /dev/serial0
option socket unix data file desciptor -1
option socket unix control file desciptor -1
opened /dev/serial0
read mode 3
mode 3 unchanged
writing version command
reading version
ERROR [?UNKNOWN? Success] timed out

unable to read version

**Comment by lloydroc** [comment]
Hello,

None of the command I previously sent will make any changes. It looks like
your /dev/serial0 soft links to /dev/ttyS0 and not /dev/ttyAMA0. Here is
what mine looks like on a working Pi 4.

Thus, your UART isn't configured correctly.

I didn't see the output of this command in your last message. It is this?
***@***.***:~ $ ls -l /dev/ttyS0
crw-rw---- 1 root dialout 4, 64 Feb 11 19:02 /dev/ttyS0

Previously, you sent the output of /dev/ttyAMA0 which is probably confusing
in the documentation because that is how it was in the Model B+. Hopefully,
you change the permissions to have what I have above for dev/ttyS0. It
should just be:
# chmod 660 /dev/ttyS0
# chown root:dailout /dev/ttyS0

When it works you'll see something like this:
***@***.***:~ $ stty -F /dev/ttyS0 -a
speed 9600 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt =
^R;
werase = ^W; lnext = ^V; discard = ^O; min = 0; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon
-ixoff
-iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0
vt0 ff0
-isig -icanon -iexten -echo echoe echok -echonl -noflsh -xcase -tostop
-echoprt
echoctl echoke -flusho -extproc
***@***.***:~ $

Cheers,
Lloyd

**Comment by Yassineelkasmy** [comment]
Thanks a lot for your engaging , unfortunately we change our project subject to another network protocol than Lora because we found a lot of issues other than this one and we don`t have a lot of time for the final deadline.
Thanks you so much for providing us this library, i will consider it in my future IoT projects.
